export interface CarType {
    "_id": string,
    "owner": string,
    "brand": string,
    "model": string,
    "image": any,
    "year": number,
    "category": string,
    "seating_capacity": number,
    "fuel_type": string,
    "transmission": string,
    "pricePerDay": number,
    "location": string,
    "description": string,
    "isAvaliable": boolean,
    "createdAt": string,
}